function [out] = f_04_twoexogproxies(theta,U_hat,z1_used,z2_used)
[n,T] = size(U_hat);

theta1 = theta(1:n-1);
theta2 = theta(n-1+1:end);

% out = [(U_hat(3:end,:)  -theta1*U_hat(1,:)    -theta2*U_hat(2,:)    )   .*z1_used;...
%        (U_hat(3:end,:)  -theta1*U_hat(1,:)    -theta2*U_hat(2,:)    )   .*z1_used.^2;...
%        (U_hat(3:end,:)  -theta1*U_hat(1,:)    -theta2*U_hat(2,:)    )   .*z2_used;...
%        (U_hat(3:end,:)  -theta1*U_hat(1,:)    -theta2*U_hat(2,:)    )   .*z2_used.^2];

out = [(U_hat(2:end,:)  -theta1*U_hat(1,:)     )   .*z1_used;...
       (U_hat(2:end,:)  -theta1*U_hat(1,:)     )   .*z1_used.^2;...
       (U_hat(2:end,:)  -theta2*U_hat(1,:)     )   .*z2_used;...
       (U_hat(2:end,:)  -theta2*U_hat(1,:)     )   .*z2_used.^2];

end